data:
  - attributes:
      created_at: '2020-12-29T15:17:58'
      destination_override_endpoint: '*'
      entries:
        - classifiers: {}
          config:
            condition: AND
            rules:
              - condition: null
                expression:
                  field: PathInfo
                  operator: equals
                  type: string
                  values:
                    - /post
              - condition: null
                expression:
                  field: ContentType
                  operator: equals
                  type: string
                  values:
                    - application/json
          id: 2e1ea6ca-d4b0-40b5-b8a2-a6e5f214c158
          id_selector: null
          operation: ENRICH
          operations: null
          phase: REQUEST
          public_token_generator: UUID
          targets:
            - body
          token_manager: PERSISTENT
          transformer: JSON_PATH
          transformer_config:
            - $.CCNum
            - $.ExpDate
            - $.CVCNum
          transformer_config_map: null
          type: null
      host_endpoint: echo\.apps\.verygood\.systems
      id: 2e3bcec0-845b-4283-af84-64f7ff62ff85
      ordinal: null
      port: 80
      protocol: http
      source_endpoint: '*'
      tags:
        name: papaya-whip-cube
        source: RouteContainer
      updated_at: '2020-12-30T02:06:37'
    id: 2e3bcec0-845b-4283-af84-64f7ff62ff85
    type: rule_chain
version: 1
